import * as fs from "node:fs";
import * as path from "node:path";
import { type ArtifactStore } from "./artifacts.ts";

export interface VaultExportResult {
  exportDir: string;
  notesCount: number;
  diagramsCount: number;
}

export class ObsidianExporter {
  private store: ArtifactStore;

  constructor(store: ArtifactStore) {
    this.store = store;
  }

  /**
   * Bundles all notes and diagrams into an Obsidian-ready folder structure with an Index.md hub.
   */
  public exportVault(targetExportDir?: string): VaultExportResult {
    const exportDir =
      targetExportDir ||
      path.join(this.store.getNotesDir(), "..", "obsidian-vault");

    const vaultNotesDir = path.join(exportDir, "Notes");
    const vaultVizDir = path.join(exportDir, "viz");

    fs.mkdirSync(vaultNotesDir, { recursive: true });
    fs.mkdirSync(vaultVizDir, { recursive: true });

    // 1. Copy all markdown notes
    const sourceNotes = this.store.getNotesDir();
    let notesCount = 0;
    const noteLinks: string[] = [];

    if (fs.existsSync(sourceNotes)) {
      const files = fs.readdirSync(sourceNotes).filter((f) => f.endsWith(".md"));
      for (const file of files) {
        fs.copyFileSync(path.join(sourceNotes, file), path.join(vaultNotesDir, file));
        notesCount++;
        noteLinks.push(`- [[${file.replace(/\.md$/, "")}]]`);
      }
    }

    // 2. Copy all diagram PNGs
    const sourceViz = this.store.getVizDir();
    let diagramsCount = 0;

    if (fs.existsSync(sourceViz)) {
      const images = fs.readdirSync(sourceViz).filter((f) => f.endsWith(".png"));
      for (const img of images) {
        fs.copyFileSync(path.join(sourceViz, img), path.join(vaultVizDir, img));
        diagramsCount++;
      }
    }

    // 3. Create Index.md hub
    const indexContent = `# Socratic Learning Vault Hub
*Exported on: ${new Date().toLocaleString()}*

Welcome to your cumulative personal knowledge base. Every lesson note, concept derivation, and verified diagram is preserved in this vault.

## Completed Lessons
${noteLinks.length > 0 ? noteLinks.join("\n") : "*No completed lesson notes yet.*"}

---
*Generated by Learn-LLM Studio*
`;

    fs.writeFileSync(path.join(exportDir, "Index.md"), indexContent, "utf8");

    return {
      exportDir,
      notesCount,
      diagramsCount,
    };
  }
}
